### ISSUE TITLE
Maven artifact snapshot version error

### ISSUE THREAD

**Issue by rashedkvm** [vmware-tanzu/tanzu-source-controller#263]
**Bug description**
Maven artifact snapshot version error when the requested version is: `1.0.0-feature-updates-SNAPSHOT`.  but it's just stripping off anything after 1.0.0 and setting it to 1.0.0-SNAPSHOT.

**Expected behavior**
Maven artifact snapshot version with: `1.0.0-feature-updates-SNAPSHOT` should not fail processing
**Steps to reproduce the bug**

**Version** (include the SHA if the version is not obvious)
- v0.8.3

**Relevant Debug Output (Logs, etc)**

```yaml
status:
  conditions:
  - lastTransitionTime: "2024-03-04T18:02:10Z"
    message: Maven artifact checksum file not found (HTTP 404) at URL "https://build-artifactory.eng.vmware.com/artifactory/com/example/demo/0.0.3-SNAPSHOT/demo-0.0.3-SNAPSHOT.jar.sha1".
    reason: RemoteError
    status: "False"
    type: ArtifactAvailable
  - lastTransitionTime: "2024-03-04T18:02:10Z"
    message: Resolved version "0.0.3-features-update-SNAPSHOT" for artifact "https://build-artifactory.eng.vmware.com/artifactory/example/demo/0.0.3-SNAPSHOT/demo-0.0.3-SNAPSHOT.jar"
    reason: Resolved
    status: "True"
    type: ArtifactVersionResolved
  - lastTransitionTime: "2024-03-04T18:02:10Z"
    message: Maven artifact checksum file not found (HTTP 404) at URL "https://build-artifactory.eng.vmware.com/artifactory/com/example/demo/0.0.3-SNAPSHOT/demo-0.0.3-SNAPSHOT.jar.sha1".
    reason: RemoteError
    status: "False"
    type: Ready
  observedGeneration: 1
```

- Maven Coordinates passed in workload.yml
```
  spec:
   params:
   - name: maven_repository_url
    value: https://artifactory.penske.com/artifactory/cf-mvn-development-local
  value:
   artifactId: sample-python-web-app
   groupId: com.penske.cicd
   type: zip
   version: 1.0.0-feature-updates-SNAPSHOT
```
 
- Maven URL created from coordinates by Supply Chain
  https://artifactory.penske.com/artifactory/cf-mvn-development-local/com/penske/cicd/sample-python-web-app/1.0.0-feature-updates-SNAPSHOT/sample-python-web-app-1.0.0-SNAPSHOT.zip (It removed feature-updates)

- Artifactory URL where item is stored in Artifactory
  https://artifactory.penske.com/artifactory/cf-mvn-development-local/com/penske/cicd/sample-python-web-app/1.0.0-feature-updates-SNAPSHOT/sample-python-web-app-1.0.0-feature-updates-SNAPSHOT.zip
