### ISSUE TITLE
`MavenArtifact` API status condition is set incorrectly.

### ISSUE THREAD

**Issue by rashedkvm** [vmware-tanzu/tanzu-source-controller#97]
**Bug description**
`MavenArtifact` API status condition is set incorrectly. Resource status stuck in `Unknown` state. This issue occurs when there are multiple resources are processed. Here is an example of the incorrect status condition
```yaml
status:
  conditions:
    - lastTransitionTime: "2023-05-19T05:30:54Z"
      message: ""
      reason: Initializing
      status: Unknown
      type: ArtifactAvailable
    - lastTransitionTime: "2023-05-19T05:30:54Z"
      message: Resolved version "0.0.1" for artifact "https://sample-maven-repository.ootb-maven-test.svc.cluster.local:8443/carto/run/hello-world/0.0.1/hello-world-0.0.1.jar"
      reason: Resolved
      status: "True"
      type: ArtifactVersionResolved
    - lastTransitionTime: "2023-05-19T05:30:54Z"
      message: ""
      reason: Initializing
      status: Unknown
      type: Ready
  observedGeneration: 1
```
**Expected behavior**
`MavenArtifact` status should reflect the proper status condition based on the artifact version and download.
**Steps to reproduce the bug**
Deploy 5-6 `MavenArtifact` resources concurrently. 
**Version** (include the SHA if the version is not obvious)
Tanzu Source Controller `v0.7.0`
**Environment where the bug was observed (cloud, OS, etc)**

**Relevant Debug Output (Logs, etc)**
```sh
{"level":"error","ts":"2023-05-18T17:00:03.653315081Z","logger":"MavenArtifactResourceReconciler","msg":"unable to update status","controller":"mavenartifact","controllerGroup":"source.apps.tanzu.vmware.com","controllerKind":"MavenArtifact","MavenArtifact":{"name":"app","namespace":"ootb-maven-test"},"namespace":"ootb-maven-test","name":"app","reconcileID":"ac6d6a25-5ef8-4198-81e7-ad43298400a3","resourceType":"source.apps.tanzu.vmware.com/v1alpha1, Kind=MavenArtifact","error":"Operation cannot be fulfilled on mavenartifacts.source.apps.tanzu.vmware.com \"app\": StorageError: invalid object, Code: 4, Key: /registry/source.apps.tanzu.vmware.com/mavenartifacts/ootb-maven-test/app, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: eb3fd308-ead3-4066-a933-dc53ab01c1fc, UID in object meta: ","stacktrace":"github.com/vmware-labs/reconciler-runtime/reconcilers.(*ResourceReconciler).Reconcile\n\tgithub.com/vmware-labs/reconciler-runtime@v0.10.0/reconcilers/reconcilers.go:262\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\tsigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:121\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:320\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:234"}
```
